#!/bin/sh
#
# A wrapper script for Blender
#

# In case user's home directory doesn't contain ~/.blender, copy it
# from /usr/share/blender

if [ ! -d ~/.blender ]; then
    install -d ~/.blender
    ln -sf /usr/share/blender/Blanguages ~/.blender/.Blanguages
    ln -sf /usr/share/blender/bfont.ttf  ~/.blender/.bfont.ttf
    cp -a /usr/share/blender/bpydata ~/.blender
    cp -a /usr/share/blender/VERSION ~/.blender

    install -d ~/.blender/plugins/sequence
    install -d ~/.blender/plugins/texture

    install -d ~/.blender/scripts
    ln -sf /usr/share/blender/scripts/* ~/.blender/scripts/
fi

#
# In case the user's ~/.blender came from older versions, some files
# should be reinstalled.
#

if [ $(cat ~/.blender/VERSION) != $(cat /usr/share/blender/VERSION) ]; then
    cp -a /usr/share/blender/bpydata ~/.blender
    ln -sf /usr/share/blender/scripts/* ~/.blender/scripts/
    cp -a /usr/share/blender/VERSION ~/.blender
fi

#
# Fully update the plugins every time blender is launched.
#

for script in /usr/share/blender/scripts/*.py* ; do
    s=`basename $script`
    if [ ! -e ~/.blender/scripts/$s ] ; then
         ln -sf $script ~/.blender/scripts
    fi
done

#
# Do the same for the scripts shipped by other packages
#

for package in /usr/share/blender/scripts.d/* ; do
    p=`basename $package`

    mkdir -p ~/.blender/scripts/$p

    for script in $package/*.py* ; do
        s=`basename $script`
        if [ ! -e ~/.blender/scripts/$s ] ; then
            ln -sf $script ~/.blender/scripts/$p
        fi
    done
done

blender-bin "$@"
