### Not doable, dh_install can't rename
#install/linux2/blender	/usr/bin/blender-bin
#debian/blender-wrapper	/usr/bin/blender

### Could be, but done in debian/rules, along the previous
#install/linux2/blenderplayer	/usr/bin

### Menus, icons
debian/misc/blender-*.desktop	/usr/share/applications
debian/misc/blender.xpm		/usr/share/pixmaps

### Freedesktop icons
release/freedesktop/icons/16x16/blender.png	/usr/share/icons/hicolor/16x16/apps
release/freedesktop/icons/22x22/blender.png	/usr/share/icons/hicolor/22x22/apps
release/freedesktop/icons/32x32/blender.png	/usr/share/icons/hicolor/32x32/apps
release/freedesktop/icons/scalable/blender.svg	/usr/share/icons/hicolor/scalable/apps

### Plugins
install/linux2/plugins/sequence/*.so	/usr/lib/blender/plugins/sequence
install/linux2/plugins/texture/*.so	/usr/lib/blender/plugins/texture

### Misc. files
release/scripts/bpydata			/usr/share/blender
release/scripts				/usr/share/blender
release/VERSION				/usr/share/blender
install/linux2/.blender/locale		/usr/share
install/linux2/.blender/.Blanguages	/usr/share/blender
